spring.application.name=basics

server.port=8081 
//8080_was_busy

//dyanamic_handling_of_componets

payment.provider = StripePay

logging.level.com.bhaskar.basics = DEBUG 
#logging.level.root = ERROR
#logging.level.root = OFF
# for above two lines only error or more severity will be the logs ->
# -> no one has more severity than ERROR , so only error will be there in logs
# or we can off it as well